#include <iostream>
#include <vector>
#include <algorithm>
#include <string>
#include <set>
#include <bitset>
#include <cmath>
#include <unordered_map>
#include <queue>
#include <functional>
#include <cstring>
using namespace std;

#define FOR(i,n) for(int i=0; i<(n); i++)
#define endl "\n"
string target;
string bomb;
char result[1000001];


void input()
{
	ios::sync_with_stdio(false);
	cin.tie(NULL);
	cout.tie(NULL);

	cin >> target >> bomb;
}

void solve()
{
	int index = 0;
	FOR(i, target.size())
	{
		result[index++] = target[i];
		int j = bomb.size();
		if (target[i] == bomb[--j])
		{
			bool isSame = false;
			int check_size = index - bomb.size();
			for (int k = index - 1; k >= check_size; k--)
			{
				if (result[k] == bomb[j--])
					isSame = true;
				else
				{
					isSame = false;
					break;
				}
			}

			if (isSame == true)
				index -= bomb.size();
		}
	}

	if (index == 0)
		cout << "FRULA" << endl;
	else
	{
		FOR(i, index)
			cout << result[i];
		cout << endl;
	}
}

int main()
{
	input();
	solve();

	return 0;
}
/*
asdlajodaiwlajbvabdkjabwdkjbacc2c24424iwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424asdlajodaiwlajbvabdkjabwdkjbaiwdubiauwdbiadbviabviuabiajblkdjahkfahwlkjdhadkwhjlkawjhdflkajhlkajwbccc242424
c24

asdlajodai
wlajbvabdk
jabwdkjbai
wdubiauwdb
iadbviabvi
uabiajblkd
jahkfahwlk
jdhadkwhjl
kawjhdflka
jhlkajwbcc
*/